- name: configuring redis
  hosts: redis
  become: true
  tasks:
    - name: enabling redis7
      command: dnf module enable redis:7 -y
    - name: installing redis
      package:
        name: redis
        state: present
    - name: starting and enabling redis
      service:
        name: redis
        state: started
        enabled: true
    - name: replace listen address
      replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
    - name: updating line of protected mode
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: 'protected-mode yes'
        line: 'protected-mode no'